const mongoose = require('mongoose');
const Region = require('./src/models/Region');

const PREDEFINED_REGION_NAMES = [
  '🟢 Valmiki Nagar Forest, Bihar',
  '🟡 Murchison Falls, Uganda',
  '🔴 Odzala-Kokoua, Congo',
  '🌲 Black Forest, Germany',
  '🏜️ Sahara Desert, Egypt',
  '🌴 Amazon Rainforest, Brazil',
  '❄️ Siberian Taiga, Russia',
  '🌾 Serengeti Plains, Tanzania',
];

async function cleanupRegions() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/hcakethon-ipec', {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    console.log('📊 Connected to MongoDB');

    // Get all regions
    const allRegions = await Region.find({});
    console.log(`\n📋 Total regions in database: ${allRegions.length}`);
    console.log('\nRegion List:');
    allRegions.forEach((r, i) => {
      const isPredefined = PREDEFINED_REGION_NAMES.includes(r.name);
      console.log(`  ${i + 1}. ${r.name} ${isPredefined ? '✅ (PREDEFINED)' : '❌ (CUSTOM)'}`);
    });

    // Delete ALL regions from database (predefined regions come from backend code)
    if (allRegions.length > 0) {
      console.log(`\n🗑️  Deleting ALL ${allRegions.length} regions from database...`);
      console.log('   (Predefined regions are auto-generated by backend code)');
      
      const result = await Region.deleteMany({});
      console.log(`\n✅ Deleted ${result.deletedCount} regions from database`);
    } else {
      console.log('\n✅ Database is already empty');
    }

// Verify deletion by checking current state
    console.log('\n⏳ Verifying deletion...');
    await new Promise(resolve => setTimeout(resolve, 500));

    // Show final count
    const finalCount = await Region.countDocuments({});
    console.log(`\n📊 Final region count: ${finalCount} (expected: 0)`);

    if (finalCount === 0) {
      console.log('✅ All custom regions successfully deleted!');
      console.log('   (Predefined regions are generated by backend, not stored in DB)');
    } else {
      // If still have regions, list them
      const remaining = await Region.find({}).sort({ name: 1 });
      console.log(`\n⚠️  ${finalCount} regions remain in database:`);
      remaining.forEach((r, i) => {
        console.log(`  ${i + 1}. ${r.name}`);
      });
    }

    await mongoose.connection.close();
    console.log('\n✅ Cleanup complete!');
    process.exit(0);

  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

cleanupRegions();
